[package]
name = "gras"
version = "0.1.2"
edition = "2024"
description = "A Genetic Programming framework for Neural Architecture Search in Rust"
license = "MIT"
homepage = "https://github.com/maulberto3/gras"

[features]
default = []
cuda = ["flodl/cuda"]

[dependencies]
fastrand = "2.5.0"
flodl = "0.7.0"

# Development profile: Optimized for fast build times and debugging.
[profile.dev]
opt-level = 0
debug = true
incremental = true
codegen-units = 256

# Release profile: Optimized for maximum runtime performance.
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
debug = false

[dev-dependencies]
git-cliff = "2.13.1"
proptest = "1.11.0"

[package.metadata.release]
pre-release-commit-message = "chore(release): bump version to {{version}}"
tag-message = "v{{version}}"
sign-tag = false
push = true
